### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by kibertoad** [wooorm/markdown-table#18]
Would you be open to having TS types in this repo if I could create them?

**Comment by wooorm** [comment]
Thanks for offering! The Microsoft team currently suggest adding types for non-typescript projects to the DefinitelyTyped project, and I side with that decision.

**Comment by kibertoad** [comment]
@wooorm What is the advantage of that approach? Isn't it easier to maintain types in-repo rather than jump through all the hoops of DefinitelyTyped process? Isn't DefinitelyTyped mostly used as a fallback solution these days?

**Comment by wooorm** [comment]
Well, the gist of it is: I am not a fan of typescript, and I get to decide how I run my own open source projects, in my free time! My experience with coffeescript/typescript is that less folks can write in them, making it harder for others to contribute. It also introduced something that I don’t use or know about into a project I maintain. Which will become a problem next year, when you aren’t interested in this project anymore.

Here is what typescript says about it: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by kibertoad** [comment]
`Here is what typescript says about it: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html`

Yeah, fair enough.

`and I get to decide how I run my own open source projects, in my free time!`

Also undeniably true.

`Which will become a problem next year, when you aren’t interested in this project anymore.`

I am not aware of an opensource project that I've abandoned in the past. You can check my GitHub history, I can assure you that I would definitely find time to update typings immediately should you ping me next year or the year after that, or as long as I'm still in this industry. However, first two reasons that you listed are still definitely valid. Thank you for clarifying your position!

**Comment by wooorm** [comment]
Glad to hear! Thanks that you’d offer that!
I was under the impression that the DefinitelyTyped project is mostly automated: it pings people who previously helped and such, so I thought “jump through all the hoops” wasn’t that many hoops!

**Comment by kibertoad** [comment]
@wooorm It is automated to an extent, but people still need to react after being pinged, and that often takes quite a bit of time. Also, considering that DefinitelyTyped is a huuuuuuuge monorepo, working with it is less than pleasant :D. So yeah.
