### ISSUE TITLE
package won't import on node v14.16.1

### ISSUE THREAD

**Issue by rustygreen** [wooorm/markdown-table#23]
### Issue
The package will not import on node version 14.16.1 (Windows 10)
```ts
import { markdownTable } from 'markdown-table';

const x = markdownTable([
  ['Branch', 'Commit'],
  ['main', '0123456789abcdef'],
  ['staging', 'fedcba9876543210']
]);
```

### Result
![image](https://user-images.githubusercontent.com/1774477/115943258-d9171280-a47c-11eb-8e9d-aa9184480ba6.png)

**Comment by wooorm** [comment]
This package is pure ESM. I added a link with more information to the readme.

**Comment by rustygreen** [comment]
Yeah, I realize it is pure ESM and am using it as an ESM module. I think it is related to ts-node (I am using ts-node). I see the README link discusses using the library with ts-node. I'll check it out. Thanks!

**Comment by droidpl** [comment]
Same here importing it with ts-node

**Comment by adam-rocska** [comment]
the lib's scripter should check `@arethetypeswrong/cli` and also how Vercel's stuff are made to work with various dependent scenarios.... 

Too bad. This lib would have been handy.
