### ISSUE TITLE
Is there any forked package that supports CommonJS

### ISSUE THREAD

**Issue by glinda93** [wooorm/markdown-table#27]
Is there any forked package that supports commonjs?

It's a pain that jest throws error: `unexpected token 'export'`

**Comment by wooorm** [comment]
Use the previous version.

**Comment by glinda93** [comment]
> Use the previous version.

Can you please point the version?

**Comment by wooorm** [comment]
https://github.com/wooorm/markdown-table/releases

The one before "Use ESM" (this major)

**Comment by glinda93** [comment]
Made my own: https://www.npmjs.com/package/markdown-table-cjs
